package com.byx.movie.mapper;

import com.byx.movie.manager.pojo.UserBase;
import com.byx.movie.manager.pojo.UserBaseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_BASE
     *
     * @mbggenerated Thu Sep 13 14:54:06 CST 2018
     */
    int countByExample(UserBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_BASE
     *
     * @mbggenerated Thu Sep 13 14:54:06 CST 2018
     */
    int deleteByExample(UserBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_BASE
     *
     * @mbggenerated Thu Sep 13 14:54:06 CST 2018
     */
    int insert(UserBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_BASE
     *
     * @mbggenerated Thu Sep 13 14:54:06 CST 2018
     */
    int insertSelective(UserBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_BASE
     *
     * @mbggenerated Thu Sep 13 14:54:06 CST 2018
     */
    List<UserBase> selectByExample(UserBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_BASE
     *
     * @mbggenerated Thu Sep 13 14:54:06 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserBase record, @Param("example") UserBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_BASE
     *
     * @mbggenerated Thu Sep 13 14:54:06 CST 2018
     */
    int updateByExample(@Param("record") UserBase record, @Param("example") UserBaseExample example);
}